# This is an example mods.toml file. It contains the data relating to the loading mods.
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[43]" #mandatory

license="All Rights Reserved"

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="carldertweaks" #mandatory
version="1.0.1" #mandatory
displayName="CarlderGross' Tweaks Mod" #mandatory
authors="CarlderGross" # A text field displayed in the mod UI, optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A small tweaks mod that fixes some annoying things about vanilla Minecraft.
'''